GameVersion: 0.221.4
ModVersion: 0.2.0
Type: Humanoid
Prefab: TrainingDummy
Character:
  name: TrainingDummy
  heatBuildupBase: 1.5
  heatCooldownBase: 1
  heatBuildupWater: 2
  heatWaterTouchMultiplier: 0.2
  lavaDamageTickInterval: 0.2
  heatLevelFirstDamageThreshold: 0.7
  lavaFirstDamage: 10
  lavaFullDamage: 100
  lavaAirDamageHeight: 3
  dayHeatGainRunning: 0.2
  dayHeatGainStill: -0.05
  dayHeatEquipmentStop: 0.5
  lavaSlowMax: 0.5
  lavaSlowHeight: 0.8
  faction: Undead
  boss: false
  dontHideBossHud: false
  aiSkipTarget: false
  crouchSpeed: 2
  walkSpeed: 0
  speed: 0
  turnSpeed: 0
  runSpeed: 0
  runTurnSpeed: 300
  acceleration: 0.5
  jumpForce: 10
  jumpForceForward: 0
  jumpForceTiredFactor: 0.7
  airControl: 0.1
  jumpStaminaUsage: 10
  flying: false
  flySlowSpeed: 5
  flyFastSpeed: 12
  flyTurnSpeed: 12
  canSwim: false
  swimDepth: 1.3
  swimSpeed: 1
  swimTurnSpeed: 100
  swimAcceleration: 0.05
  groundTilt: None
  groundTiltSpeed: 50
  disableWhileSleeping: false
  useAltStatusEffectScaling: false
  tolerateWater: true
  tolerateFire: false
  tolerateSmoke: true
  tolerateTar: false
  hitEffects:
    effectPrefabs:
    - prefab: vfx_draugr_hit
    - prefab: sfx_trainingdummy_light_attack impact
  critHitEffects:
    effectPrefabs:
    - prefab: fx_crit
  backstabHitEffects:
    effectPrefabs:
    - prefab: fx_backstab
  deathEffects:
    effectPrefabs:
    - prefab: vfx_draugr_death
    - prefab: sfx_trainingdummy_stagger
    - prefab: Draugr_ragdoll
  waterEffects:
    effectPrefabs:
    - prefab: vfx_water_surface
      attach: true
  health: 40000
  regenAllHPTime: 3600
  damageModifiers:
    chop: Immune
    pickaxe: Immune
  staggerWhenBlocked: true
  staggerDamageFactor: 0
  enemyAdrenalineMultiplier: 1
  defaultItems:
  - TrainingDummy_attack
  - TrainingDummy_throw
  attacks:
  - prefab: TrainingDummy_attack
    name: dummy attack
    maxStackSize: 1
    maxQuality: 1
    scaleByQuality: 0
    weight: 1
    scaleWeightByQuality: 0
    value: 0
    teleportable: true
    toolTier: 0
    damages:
      damage: 1
    attackForce: 60
    backstabBonus: 4
    dodgeable: true
    blockable: true
    tamedOnly: false
    attack:
      attackType: Vertical
      attackAnimation: attack_light
      attackRandomAnimations: 0
      attackChainLevels: 0
      loopingAttack: false
      consumeItem: false
      hitTerrain: true
      attackHealthReturnHit: 0
      attackKillsSelf: false
      speedFactor: 0.3
      speedFactorRotation: 1
      attackStartNoise: 10
      attackHitNoise: 30
      damageMultiplier: 1
      # For each missing health point, increase damage this much.
      damageMultiplierPerMissingHP: 0
      # At 100% missing HP the damage will increase by this much, and gradually inbetween.
      damageMultiplierByTotalHealthMissing: 0
      # For each missing health point, return one stamina point.
      staminaReturnPerMissingHP: 0
      forceMultiplier: 1
      staggerMultiplier: 1
      recoilPushback: 0
      selfDamage: 0
      attackRange: 3
      attackHeight: 1.2
      attackHeightChar1: 0
      attackHeightChar2: 0
      attackOffset: 0
      toggleFlying: false
      attach: false
      cantUseInDungeon: false
      # Loading
      requiresReload: false
      reloadTime: 2
      # Draw
      bowDraw: false
      drawDurationMin: 0
      drawStaminaDrain: 0
      drawEitrDrain: 0
      # Melee/AOE
      attackAngle: 45
      attackRayWidth: 0.7
      attackRayWidthCharExtra: 0
      maxYAngle: 0
      lowerDamagePerHit: true
      hitPointtype: Closest
      hitThroughWalls: false
      multiHit: true
      pickaxeSpecial: false
      lastChainDamageMultiplier: 2
      resetChainIfHit: None
      spawnOnHitChance: 0
      projectileVel: 10
      projectileVelMin: 2
      # When not using Draw, randomize velocity between Velocity and Velocity Min
      randomVelocity: false
      projectileAccuracy: 10
      projectileAccuracyMin: 20
      circularProjectileLaunch: false
      distributeProjectilesAroundCircle: false
      useCharacterFacing: false
      useCharacterFacingYAim: false
      launchAngle: 0
      projectiles: 1
      projectileBursts: 1
      burstInterval: 0
      destroyPreviousProjectile: false
      perBurstResourceUsage: false
    aiAttackRange: 1.8
    aiAttackRangeMin: 0
    aiAttackInterval: 2
    aiAttackMaxAngle: 20
    aiInvertAngleCheck: false
    aiWhenFlying: true
    aiWhenFlyingAltitudeMin: 0
    aiWhenWalking: true
    aiWhenSwiming: true
    aiPrioritized: false
    aiInDungeonOnly: false
    aiInMistOnly: false
    aiMinHealthPercentage: 0
    aiTargetType: Enemy
    hitEffect:
      effectPrefabs:
      - prefab: vfx_HitSparks
      - prefab: sfx_trainingdummy_light_attack impact
    startEffect:
      effectPrefabs:
      - prefab: sfx_trainingdummy_light_attack
  - prefab: TrainingDummy_throw
    name: dummy throw stone
    maxStackSize: 1
    maxQuality: 1
    scaleByQuality: 0
    weight: 1
    scaleWeightByQuality: 0
    value: 0
    teleportable: true
    toolTier: 0
    damages:
      damage: 1
    attackForce: 30
    backstabBonus: 4
    dodgeable: true
    blockable: true
    tamedOnly: false
    attack:
      attackType: Projectile
      attackAnimation: attack_throw
      attackRandomAnimations: 0
      attackChainLevels: 0
      loopingAttack: false
      consumeItem: false
      hitTerrain: true
      attackHealthReturnHit: 0
      attackKillsSelf: false
      speedFactor: 0
      speedFactorRotation: 0
      attackStartNoise: 10
      attackHitNoise: 30
      damageMultiplier: 1
      # For each missing health point, increase damage this much.
      damageMultiplierPerMissingHP: 0
      # At 100% missing HP the damage will increase by this much, and gradually inbetween.
      damageMultiplierByTotalHealthMissing: 0
      # For each missing health point, return one stamina point.
      staminaReturnPerMissingHP: 0
      forceMultiplier: 1
      staggerMultiplier: 1
      recoilPushback: 0
      selfDamage: 0
      attackRange: 0.8
      attackHeight: 1.5
      attackHeightChar1: 0
      attackHeightChar2: 0
      attackOffset: 0
      toggleFlying: false
      attach: false
      cantUseInDungeon: false
      # Loading
      requiresReload: false
      reloadTime: 2
      # Draw
      bowDraw: false
      drawDurationMin: 0
      drawStaminaDrain: 0
      drawEitrDrain: 0
      # Melee/AOE
      attackAngle: 0
      attackRayWidth: 0
      attackRayWidthCharExtra: 0
      maxYAngle: 0
      lowerDamagePerHit: true
      hitPointtype: Closest
      hitThroughWalls: false
      multiHit: true
      pickaxeSpecial: false
      lastChainDamageMultiplier: 2
      resetChainIfHit: None
      spawnOnHitChance: 0
      attackProjectile: TrainingDummy_throw_projectile
      projectileRef:
        prefab: TrainingDummy_throw_projectile
        type: Physical
        damage: {}
        aoe: 0
        dodgeable: false
        blockable: false
        attackForce: 0
        backstabBonus: 4
        healthReturn: 0
        ttl: 4
        hitNoise: 50
        hitEffects:
          effectPrefabs:
          - prefab: sfx_trainingdummy_throw_impact
          - prefab: vfx_arrowhit
        # Bounce
        bounce: false
        bounceOnWater: false
        # Spawn on Hit
        respawnItemOnHit: false
        spawnOnTtl: false
        spawnOnHitChance: 1
        spawnCount: 1
        randomSpawnOnHitCount: 1
        randomSpawnSkipLava: false
        staticHitOnly: false
        groundHitOnly: false
        spawnRandomRotation: false
        spawnFacingRotation: false
        # Projectile Spawning
        spawnProjectileNewVelocity: false
        spawnProjectileMinVel: 1
        spawnProjectileMaxVel: 5
        spawnProjectileRandomDir: 0
        spawnProjectileHemisphereDir: false
        projectilesInheritHitData: false
        onlySpawnedProjectilesDealDamage: false
        divideDamageBetweenProjectiles: false
      projectileVel: 12
      projectileVelMin: 2
      # When not using Draw, randomize velocity between Velocity and Velocity Min
      randomVelocity: false
      projectileAccuracy: 5
      projectileAccuracyMin: 5
      circularProjectileLaunch: false
      distributeProjectilesAroundCircle: false
      useCharacterFacing: false
      useCharacterFacingYAim: false
      launchAngle: -25
      projectiles: 1
      projectileBursts: 1
      burstInterval: 0
      destroyPreviousProjectile: false
      perBurstResourceUsage: false
    aiAttackRange: 12
    aiAttackRangeMin: 3.01
    aiAttackInterval: 6
    aiAttackMaxAngle: 5
    aiInvertAngleCheck: false
    aiWhenFlying: false
    aiWhenFlyingAltitudeMin: 0
    aiWhenWalking: true
    aiWhenSwiming: true
    aiPrioritized: true
    aiInDungeonOnly: false
    aiInMistOnly: false
    aiMinHealthPercentage: 0
    aiTargetType: Enemy
    startEffect:
      effectPrefabs:
      - prefab: sfx_trainingdummy_throw
AI:
  alertRange: 10
  fleeIfHurtWhenTargetCantBeReached: false
  fleeUnreachableSinceAttacking: 30
  fleeUnreachableSinceHurt: 20
  fleeIfNotAlerted: false
  fleeIfLowHealth: 0
  fleeTimeSinceHurt: 20
  fleeInLava: true
  fleePheromoneMin: 3
  fleePheromoneMax: 8
  circulateWhileCharging: false
  circulateWhileChargingFlying: false
  enableHuntPlayer: false
  attackPlayerObjects: true
  privateAreaTriggerTreshold: 4
  interceptTimeMax: 0
  interceptTimeMin: 0
  maxChaseDistance: 0
  minAttackInterval: 0
  circleTargetInterval: 0
  circleTargetDuration: 5
  circleTargetDistance: 10
  sleeping: false
  wakeupRange: 5
  noiseWakeup: false
  maxNoiseWakeupRange: 50
  wakeUpDelayMin: 0
  wakeUpDelayMax: 0
  fallAsleepDistance: 0
  avoidLand: false
  consumeRange: 2
  consumeSearchRange: 5
  consumeSearchInterval: 10
  viewRange: 30
  viewAngle: 90
  hearRange: 9999
  mistVision: false
  alertedEffects:
    effectPrefabs:
    - prefab: sfx_trainingdummy_alert
  idleSound:
    effectPrefabs:
    - prefab: sfx_trainingdummy_idle
  idleSoundInterval: 10
  idleSoundChance: 0.5
  pathAgentType: HumanoidNoSwim
  moveMinAngle: 90
  smoothMovement: true
  serpentMovement: false
  serpentTurnRadius: 20
  jumpInterval: 0
  randomCircleInterval: 2
  randomMoveInterval: 10
  randomMoveRange: 10
  randomFly: false
  chanceToTakeoff: 1
  chanceToLand: 1
  groundDuration: 10
  airDuration: 10
  maxLandAltitude: 5
  takeoffTime: 5
  flyAltitudeMin: 3
  flyAltitudeMax: 10
  flyAbsMinAltitude: 32
  avoidFire: false
  afraidOfFire: false
  avoidWater: true
  avoidLava: true
  skipLavaTargets: false
  avoidLavaFlee: true
  aggravatable: false
  passiveAggresive: false
  fleeRange: 25
  fleeAngle: 45
  fleeInterval: 2
Visuals:
  scale:
    x: 1
    y: 1
    z: 1
  renderers:
  - prefab: eye_l
    active: true
    enabled: true
    materials:
    - name: draugr_eyes
      shader: Standard
      color: '#33FF00FF'
      emissionColor: '#4BFFF7FF'
  - prefab: evil_smoke
    active: true
    enabled: true
    materials:
    - name: green_smoke
      shader: Lux Lit Particles/ Bumped
      color: '#FFFFFFFF'
      emissionColor: '#000000FF'
      mainTexture: dirt
  - prefab: eye_r
    active: true
    enabled: true
    materials:
    - name: draugr_eyes
      shader: Standard
      color: '#33FF00FF'
      emissionColor: '#4BFFF7FF'
  - prefab: evil_smoke
    active: true
    enabled: true
    materials:
    - name: green_smoke
      shader: Lux Lit Particles/ Bumped
      color: '#FFFFFFFF'
      emissionColor: '#000000FF'
      mainTexture: dirt
  - prefab: Cube.001
    active: true
    enabled: true
    materials:
    - name: draugrmaterial
      shader: Custom/Creature
      color: '#FFFFFFFF'
      hue: 0
      saturation: 0
      value: 0
      emissionColor: '#000000FF'
      mainTexture: draugr_diffuse
Drops:
  drops:
  - prefab: Entrails
    amountMin: 1
    amountMax: 1
    chance: 0.5
    onePerPlayer: false
    dontScale: false
  - prefab: TrophyDraugr
    amountMin: 1
    amountMax: 1
    chance: 0.1
    onePerPlayer: false
    dontScale: false
